language: julia
julia:
  - 1.3

codecov: true

script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'

  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'

  - export DOCUMENTER_DEBUG="true"
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("Charlie_mtg");'

  - julia --project=docs/ --color=yes 'docs/make.jl'

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg;
                     cd(Pkg.dir("Charlie_mtg"));
                     Pkg.add("Coverage");
                     using Coverage;
                     Codecov.submit(Codecov.process_folder())'
